version: '3.3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
    container_name: sql-server
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Password_Challenge123!
      SSQL_PID: Express
    volumes:
      - ./resources/backup:/var/opt/mssql/backup